<?php
require "classes/models/author-model.php";
require "classes/models/book-model.php";
require "classes/models/genre-model.php";
require "classes/models/user-model.php";
require "classes/views/bookstore-view.php";
require "controllers/controller.php";

header("Content-Type: application/json");
    header('Access-Control-Allow-Origin: *');
    header('Access-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS');
    header('Access-Control-Allow-Headers: Content-Type, Accept');
$request = $_SERVER['REQUEST_URI'];
$method = $_SERVER['REQUEST_METHOD'];
$bookstoreView = new BookstoreView();
$authorModel = new AuthorModel();
$bookModel = new BookModel();
$genreModel = new GenreModel();
$userModel = new UserModel();
$controler = new Controller($bookstoreView, $method);
$controler->addRoute("authors", $authorModel, "getAllAuthors", "GET");
$controler->addRoute("genres", $genreModel, "getAllGenres", "GET");
$controler->addRoute("books", $bookModel, "getAllBooks", "GET");
$controler->addRoute("books/", $bookModel, "getSingleBook", "GET");
$controler->addRoute("users", $userModel, "getAllUsers", "GET");
$controler->addRoute("books", $bookModel, "addBook", "POST");
$controler->addRoute("books/", $bookModel, "updateBook", "PUT");
$controler->addRoute("books/", $bookModel, "deleteBook", "DELETE");
// // $controler->addRoute("sellers", $sellerModel, "addSeller", "POST");
// // $controler->addRoute("products/", $productModel, "getOneProduct", "GET");
// // $controler->addRoute("products/", $productModel, "addSellingDate", "PUT");
// // $controler->addRoute("products", $productModel, "addProduct", "POST");
$controler->start($request);