<?php
require "classes/models/author-model.php";
require "classes/models/book-model.php";
require "classes/models/genre-model.php";
require "classes/models/user-model.php";
require "classes/views/bookstore-view.php";
require "controllers/controller.php";

header("Content-Type: application/json");
$request = $_SERVER['REQUEST_URI'];
$method = $_SERVER['REQUEST_METHOD'];
// // $sellerModel = new SellerModel();
// // $productModel = new ProductModel();
// // $secondhandApi = new SecondhandApi();
$bookstoreView = new BookstoreView();
$authorModel = new AuthorModel();
$bookModel = new BookModel();
$genreModel = new GenreModel();
$userModel = new UserModel();
$controler = new Controller($bookstoreView, $method);
$controler->addRoute("authors", $authorModel, "getAllAuthors", "GET");
$controler->addRoute("genres", $genreModel, "getAllGenres", "GET");
$controler->addRoute("books", $bookModel, "getAllBooks", "GET");
$controler->addRoute("users", $userModel, "getAllUsers", "GET");
// $controler->addRoute("sellers/", $sellerModel, "getOneSeller", "GET");
// // $controler->addRoute("sellers", $sellerModel, "addSeller", "POST");
// // $controler->addRoute("products/", $productModel, "getOneProduct", "GET");
// // $controler->addRoute("products/", $productModel, "addSellingDate", "PUT");
// // $controler->addRoute("products", $productModel, "addProduct", "POST");
$controler->start($request);